Revert "Remove exit"
This reverts commit 53d4291a9249073192630318de867309b2aca4b5.

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -24,4 +24,6 @@ jobs:
 
       - name: Ensure version bump
         if: ${{ format('v{0}', steps.read_toml.outputs.value) }} == ${{ env.LAST_TAG }}
-        run: echo "::error file=pyproject.toml, line=3::Current package version matches last release tag. This must be bumped before merging!"
+        run: |
+          echo "::error file=pyproject.toml, line=3::Current package version matches last release tag. This must be bumped before merging!"
+          exit 1
